# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmoslogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserId',
            new_name='userLoginInfo',
        ),
    ]
